"""Initial schema

Revision ID: bd28d30fdb76
Revises: 
Create Date: 2026-08-31 10:16:02.253584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd28d30fdb76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('routeNumber', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('estimatedDurationMin', sa.Integer(), nullable=True),
    sa.Column('totalDistanceKm', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('frequencyMinutes', sa.Integer(), nullable=True),
    sa.Column('operatingHours', sa.String(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('pathCoordinates', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('driverLicense', sa.String(), nullable=True),
    sa.Column('studentId', sa.String(), nullable=True),
    sa.Column('staffId', sa.String(), nullable=True),
    sa.Column('favoriteStopIds', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('buses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('busNumber', sa.String(), nullable=True),
    sa.Column('plateNumber', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('currentOccupancy', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assignedDriverId', sa.String(), nullable=True),
    sa.Column('currentRouteId', sa.String(), nullable=True),
    sa.Column('fuelLevel', sa.Integer(), nullable=True),
    sa.Column('lastInspectionDate', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assignedDriverId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['currentRouteId'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buses_id'), 'buses', ['id'], unique=False)
    op.create_table('stops',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=True),
    sa.Column('stopName', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('scheduledArrivalDeltaMin', sa.Integer(), nullable=True),
    sa.Column('landmark', sa.String(), nullable=True),
    sa.Column('isHostel', sa.Boolean(), nullable=True),
    sa.Column('isAcademicBlock', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stops_id'), 'stops', ['id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('busId', sa.String(), nullable=True),
    sa.Column('driverId', sa.String(), nullable=True),
    sa.Column('routeId', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('startTime', sa.String(), nullable=True),
    sa.Column('endTime', sa.String(), nullable=True),
    sa.Column('gpsActive', sa.Boolean(), nullable=True),
    sa.Column('currentLatitude', sa.Float(), nullable=True),
    sa.Column('currentLongitude', sa.Float(), nullable=True),
    sa.Column('currentStopIndex', sa.Integer(), nullable=True),
    sa.Column('nextStopIndex', sa.Integer(), nullable=True),
    sa.Column('passengerCount', sa.Integer(), nullable=True),
    sa.Column('distanceCoveredKm', sa.Float(), nullable=True),
    sa.Column('speedKmH', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('lastLocationUpdateTime', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['busId'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['driverId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['routeId'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_table('stop_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trip_id', sa.String(), nullable=True),
    sa.Column('route_id', sa.String(), nullable=True),
    sa.Column('stop_id', sa.String(), nullable=True),
    sa.Column('arrival_timestamp', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stop_events_arrival_timestamp'), 'stop_events', ['arrival_timestamp'], unique=False)
    op.create_index(op.f('ix_stop_events_id'), 'stop_events', ['id'], unique=False)
    op.create_index(op.f('ix_stop_events_trip_id'), 'stop_events', ['trip_id'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trip_id', sa.String(), nullable=True),
    sa.Column('bus_id', sa.String(), nullable=True),
    sa.Column('route_id', sa.String(), nullable=True),
    sa.Column('driver_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('gps_accuracy_m', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('trip_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_id'), 'telemetry', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_timestamp'), 'telemetry', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_trip_id'), 'telemetry', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_trip_id'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_timestamp'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_id'), table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index(op.f('ix_stop_events_trip_id'), table_name='stop_events')
    op.drop_index(op.f('ix_stop_events_id'), table_name='stop_events')
    op.drop_index(op.f('ix_stop_events_arrival_timestamp'), table_name='stop_events')
    op.drop_table('stop_events')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_stops_id'), table_name='stops')
    op.drop_table('stops')
    op.drop_index(op.f('ix_buses_id'), table_name='buses')
    op.drop_table('buses')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_table('routes')
    # ### end Alembic commands ###
